type ErrorCodes =
  | 'INVALID_ROLE'
  | 'INVALID_RESOURCE'
  | 'INVALID_PERMISSION'
  | 'INVALID_PERMISSIONS'
  | 'NO_PERMISSIONS'
  | 'MISSING_RESOURCE'
  | 'MISSING_ACTION'
  | 'UNAUTHORIZED';

export type { ErrorCodes };
